### PR TITLE
update(README.md)

### PR DESCRIPTION
**Pull request by shahabganji**
Adding a link to related projects for aurelia-time value converter package for Aurelia

### CODE REVIEW

**Comment by shahabganji** [comment]
Dear @fingerpich,
I just updated the README.md file, and have no idea why travis didn't pass as it doesn't say anything in the log files, may I ask you to take a look.

Best regards,
Shahab

**Comment by fingerpich** [comment]
Hi shahab,

I think you have forked an invalid version of jalali moment
actually I have changed it a lot and release version 3 which is more the same as moment js
you could add your library link in "How to use jalali moment in" part in README

**Comment by shahabganji** [comment]
Hi Mojtaba (@fingerpich)

May I ask yo to add a link to my project( [aurelia-time](https://github.com/shahabganji/aurelia-time) ) in your DOCUMENT or README file a we that Aurelia developers could easily find related tools juss angular developers do.

Thanks in advance

**Comment by fingerpich** [comment]
The problem is related to travis not your commit [ref](https://github.com/travis-ci/travis-ci/issues/6441)
please do it again as your friend did I will merge it.

**Comment by shahabganji** [comment]
Can I put a reference to my library in your library's README.md, if yes I can do it again, otherwise my friends request sounds adequate.

**Comment by fingerpich** [comment]
Could you provide an example of using jalali-moment in aurelia using your library like [using jalali-moment in angular](https://github.com/fingerpich/jalali-moment/blob/master/Document.md#angular-2-or-4) in Document.md after Angular?

**Comment by shahabganji** [comment]
Yes  I will within next few days :+1:

**Pull request closed without merging**
